[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.52", features = ["full"] }
proc-macro2 = "1.0.78"
